export const navData = [
  { label: "국회운영위원회" },
  { label: "법제사법위원회" },
  { label: "정무위원회" },
  { label: "기획재정위원회" },
  { label: "교육위원회" },
  { label: "과학기술정보방송통신위원회" },
  { label: "외교통일위원회" },
  { label: "국방위원회" },
  { label: "행정안전위원회" },
  { label: "문화체육관광위원회" },
  { label: "농림축산식품해양수산위원회" },
  { label: "산업통상자원중소벤처기업위원회" },
  { label: "보건복지위원회" },
  { label: "환경노동위원회" },
  { label: "국토교통위원회" },
  { label: "정보위원회" },
  { label: "여성가족위원회" },
];
